databases:
  - name: django_ml
    plan: free
    databaseName: django_ml_db
    user: postgres

services:
  - type: web
    plan: free
    name: django_ml
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_ml.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_ml
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4